#!/usr/bin/env bash

set -e

# Install dependencies
sudo pacman -Syu base-devel libffi --noconfirm

# Install yay
cd /tmp \
&& git clone https://aur.archlinux.org/yay.git \
&& cd yay \
&& makepkg -si --noconfirm

# Install applications
yay -S  --noconfirm --nomakepkgconf \
    htop \
    mlocate \
    throttled \
    unrar \
    dnsutils \
    fluxgui \
    pwgen \
    bash-completion \
    xclip \
    nmap \
    curl \
    jq \
    unzip \
    git \
    nmap \
    tig \
    tmux \
    mate-sensors-applet \
    progress \
    vim \
    python-pip \
    ca-certificates \
    ruby \
    zoom \
    ulauncher \
    balena-etcher \
    slack-desktop \
    google-chrome \
    docker \
    diodon \
    docker-compose \
    spotify \
    awless \
    vegeta \
    aws-cli \
    python-virtualenvwrapper \
    terraform-docs-bin \
    stern-bin \
    kube-ps1 \
    nvm \
    kubectx-git \
    visual-studio-code-bin \
    steam \
    bitwarden-cli \
    gnu-netcat \
    iftop \
    mtr \
    pcsx2\
    sublime-text-3-imfix \
    pcsxr 

# Add $USER to docker group
sudo usermod -aG docker $USER

# Enable throttled fix service
sudo systemctl enable --now lenovo_fix.service

# Setup preferences on gemrc
echo 'gem: --user-install' > ~/.gemrc

# Install terraforming, landscape and github_changelog_generator
gem install \
  terraforming \
  terraform_landscape \
  github_changelog_generator \
&& source virtualenvwrapper.sh

# Check if ssh and terraform dirs exists
if [[ ${HOME}/.ssh ]]; then
  mkdir ${HOME}/.ssh
  mkdir ${HOME}/terraform
fi

# Link application settings and source .bashrc
ln -s ${HOME}/dotfiles/configs/.gitconfig ${HOME}/.gitconfig
ln -s ${HOME}/dotfiles/configs/.tmux.conf ${HOME}/.tmux.conf
cp configs/config ${HOME}/.ssh/config

# Source custom_bashrc as root
if ! sudo grep -w '.custom_bashrc' /root/.bashrc; then
  echo "source ${HOME}/dotfiles/.custom_bashrc" | sudo tee -a /root/.bashrc
fi

# Source custom_bashrc as user
if ! grep -w '.custom_bashrc' ${HOME}/.bashrc; then
  echo "source ${HOME}/dotfiles/.custom_bashrc" >> ${HOME}/.bashrc
fi

# Source bash config
source ${HOME}/.bashrc
