#!/usr/bin/env bash

set -e

# Install dependencies
sudo pacman -Syu base-devel libffi pacaur --noconfirm

# Install applications
pacaur -S  --noconfirm --noedit \
    htop \
    pwgen \
    xclip \
    nmap \
    curl \
    jq \
    unzip \
    git \
    nmap \
    tig \
    tmux \
    progress \
    vim \
    python-pip \
    ca-certificates \
    ruby \
    zoom \
    ulauncher \
    balena-etcher \
    slack-desktop \
    google-chrome \
    docker \
    diodon \
    docker-compose \
    spotify \
    awless \
    vegeta \
    aws-cli \
    python-virtualenvwrapper \
    terraform-docs-bin \
    stern-bin \
    kube-ps1 \
    nvm \
    kubectx-git \
    sublime-text-3-imfix \
    visual-studio-code-bin \
    steam \
    bitwarden-cli \
    pcsxr \
    pcsx2-git 

# Add $USER to docker group
sudo usermod -aG docker $USER

# Setup preferences on gemrc
echo 'gem: --user-install' > ~/.gemrc

# Install terraforming, landscape and github_changelog_generator
gem install \
  terraforming \
  terraform_landscape \
  github_changelog_generator \
&& source virtualenvwrapper.sh

# Link application settings and source the source .bashrc
ln -s ${HOME}/dotfiles/configs/.gitconfig ${HOME}/.gitconfig
ln -s ${HOME}/dotfiles/configs/.tmux.conf ${HOME}/.tmux.conf
cp configs/config ${HOME}/.ssh

# Source custom_bashrc as root
if ! sudo grep -w '.custom_bashrc' /root/.bashrc; then
  echo "source ${HOME}/dotfiles/.custom_bashrc" | sudo tee -a /root/.bashrc
fi

# Source custom_bashrc as user
if ! grep -w '.custom_bashrc' ${HOME}/.bashrc; then
  echo "source ${HOME}/dotfiles/.custom_bashrc" >> ${HOME}/.bashrc
fi

# Source bash config
source ${HOME}/.bashrc
