[general]
import = [
  "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[window]
opacity = 0.9

[font]
size = 14

[selection]
save_to_clipboard = true

[scrolling]
history = 100000
multiplier = 3

[env]
term = "xterm-256color"
